//******************************************************************************
// SCICHART® Copyright SciChart Ltd. 2011-2018. All rights reserved.
//
// Web: http://www.scichart.com
// Support: support@scichart.com
// Sales:   sales@scichart.com
//
// SciChart.h is part of SCICHART®, High Performance Scientific Charts
// For full terms and conditions of the license, see http://www.scichart.com/scichart-eula/
//
// This source code is protected by international copyright law. Unauthorized
// reproduction, reverse-engineering, or distribution of all or any portion of
// this source code is strictly prohibited.
//
// This source code contains confidential and proprietary trade secrets of
// SciChart Ltd., and should at no time be copied, transferred, sold,
// distributed or made available without express written permission.
//******************************************************************************

#import <UIKit/UIKit.h>

//! Project version number for SciChart.
FOUNDATION_EXPORT double SciChartVersionNumber;

//! Project version string for SciChart.
FOUNDATION_EXPORT const unsigned char SciChartVersionString[];

#import <SciChart/SCIAnchorPointAnnotation.h>
#import <SciChart/SCIDataType.h>
#import <SciChart/SCIEnumerationConstants.h>
#import <SciChart/SCIBrush2D.h>
#import <SciChart/SCIAxisDeltaProtocol.h>
#import <SciChart/SCITickCoordinatesProviderDefault.h>
#import <SciChart/SCIArrayController.h>
#import <SciChart/SCICoordinateCalculatorFactory.h>
#import <SciChart/SCIAxisBase.h>
#import <SciChart/SCIRenderSurface.h>
#import <SciChart/SCINumericDeltaCalculatorBase.h>
#import <SciChart/SCIDoubleAxisDelta.h>
#import <SciChart/SCIRenderContext2D.h>
#import <SciChart/SCIInvalidatableElementProtocol.h>
#import <SciChart/SCIResamplingMode.h>
#import <SciChart/SCITickCoordinatesProviderProtocol.h>
#import <SciChart/SCICallbackBlock.h>
#import <SciChart/SCIAxis2DProtocol.h>
#import <SciChart/SCIFloatRange.h>
#import <SciChart/SCIPathColor.h>
#import <SciChart/SCIAxisInteractivityHelper.h>
#import <SciChart/SCIRangeFactory.h>
#import <SciChart/SCINiceDoubleScale.h>
#import <SciChart/SCINumericDeltaCalculator.h>
#import <SciChart/SCIAxisCollection.h>
#import <SciChart/SCITickLabel.h>
#import <SciChart/SCIAxisCore.h>
#import <SciChart/SCIAxisCoreProtocol.h>
#import <SciChart/SCIPen2D.h>
#import <SciChart/SCICoordinateCalculatorProtocol.h>
#import <SciChart/SCIIntegerRange.h>
#import <SciChart/SCINumericAxis.h>
#import <SciChart/SCIPointSeries.h>
#import <SciChart/SCITickCoordinates.h>
#import <SciChart/SCINiceScale.h>
#import <SciChart/SCIAxisEnums.h>
#import <SciChart/SCIDoubleRange.h>
#import <SciChart/SCIRenderableSeriesProtocol.h>
#import <SciChart/SCIAxisParams.h>
#import <SciChart/SCIDefaultTickLabel.h>
#import <SciChart/SCIDataDistributionCalculatorBase.h>
#import <SciChart/SCIDeltaCalculatorProtocol.h>
#import <SciChart/SCIDataSeries.h>
#import <SciChart/SCIRangeProtocol.h>
#import <SciChart/SCIXyDataSeries.h>
#import <SciChart/SCIDataDistributionCalculatorProtocol.h>
#import <SciChart/SCIIndexRange.h>
#import <SciChart/SCINumericTickLabel.h>
#import <SciChart/SciChart.h>
#import <SciChart/SCIBrushSolid.h>
#import <SciChart/SCIOpenGLBrush.h>
#import <SciChart/SCIRenderSurfaceBase.h>
#import <SciChart/SCIAxisArea.h>
#import <SciChart/SCIChartSurface.h>
#import <SciChart/SCIBrushLinearGradient.h>
#import <SciChart/SCIChartSurfaceViewBase.h>
#import <SciChart/SCIOpenGLRenderSurface.h>
#import <SciChart/SCIMetalRenderSurface.h>

#import <SciChart/SCIPenSolid.h>
#import <SciChart/SCIRenderSurfaceCallbackDelegate.h>
#import <SciChart/SCIAxisDragModifierBase.h>
#import <SciChart/SCIChartModifierProtocol.h>
#import "SCIGestureEventsHandlerProtocol.h"
#import <SciChart/SCIChartModifierBase.h>
#import <SciChart/SCIChartModifierCollection.h>
#import <SciChart/SCIXAxisDragModifier.h>
#import <SciChart/SCIYAxisDragModifier.h>
#import <SciChart/SCIZoomPanModifier.h>
#import <SciChart/SCIZoomPanModifierBase.h>
#import <SciChart/SCIRelativeZoomModifierBase.h>
#import <SciChart/SCIPinchZoomModifier.h>
#import <SciChart/SCIPanModifier.h>
#import <SciChart/SCIFastLineRenderableSeries.h>
#import <SciChart/SCIRenderableSeriesBase.h>
#import <SciChart/SCIPointSeries.h>
#import <SciChart/SCIUserDefinedDistributionCalculator.h>
#import <SciChart/SCIGenericType.h>
#import <SciChart/SCIDateRange.h>
#import <SciChart/SCIDateTimeDeltaCalculator.h>
#import <SciChart/SCITimeSpanAxisBase.h>
#import <SciChart/SCIDateTimeAxis.h>
#import <SciChart/SCITimeSpanDelta.h>
#import <SciChart/SCITimeSpanDeltaCalculatorBase.h>
#import <SciChart/SCIDateDeltaCalculatorProtocol.h>
#import <SciChart/SCIDateIntervalUtil.h>
#import <SciChart/SCIDateUtil.h>
#import <SciChart/SCIFastMountainRenderableSeries.h>
#import <SciChart/SCINiceTimeSpanScale.h>
#import <SciChart/SCIAxisStyle.h>
#import <SciChart/SCITextFormattingStyle.h>
#import <SciChart/SCIMountainSeriesStyle.h>
#import <SciChart/SCILineSeriesStyle.h>
#import <SciChart/SCIPenLinearGradient.h>
#import <SciChart/SCIRenderSurfaceStyle.h>
#import <SciChart/SCILinearGradientBrush.h>
#import <SciChart/SCIZoomExtentsModifier.h>
#import <SciChart/SCIFastCandlestickRenderableSeries.h>
#import <SciChart/SCIHlcPointSeries.h>
#import <SciChart/SCIOhlcPointSeries.h>
#import <SciChart/SCIOhlcDataSeries.h>
#import "SCIHlDataSeries.h"
#import <SciChart/SCICandlestickSeriesStyle.h>
#import <SciChart/SCIFastOhlcRenderableSeries.h>
#import <SciChart/SCIOhlcSeriesStyle.h>
#import <SciChart/SCIEllipsePointMarker.h>
#import <SciChart/SCIPointMarkerBase.h>
#import <SciChart/SCISquarePointMarker.h>
#import <SciChart/SCITrianglePointMarker.h>
#import <SciChart/SCIPointMarker.h>
#import <SciChart/SCICrossPointMarker.h>
#import <SciChart/SCIXyScatterRenderableSeries.h>
#import <SciChart/SCIPointMarkerClusterizer.h>
#import <SciChart/SCIScatterSeriesStyle.h>
#import <SciChart/SCIFastColumnRenderableSeries.h>
#import <SciChart/SCIColumnSeriesStyle.h>
#import <SciChart/SCIPointMarkerHitTestProvider.h>
#import <SciChart/SCIHitTestProviderBase.h>
#import <SciChart/SCICursorModifier.h>
#import <SciChart/SCITooltipModifier.h>
#import <SciChart/SCIXySeriesInfo.h>
#import <SciChart/SCICursorModifierStyle.h>
#import <SciChart/SCIXySeriesDataView.h>
#import <SciChart/SCIHitTestProvider.h>
#import <SciChart/SCITooltipView.h>
#import <SciChart/SCISeriesInfo.h>
#import <SciChart/SCILineHitTestProvider.h>
#import <SciChart/SCIRolloverModifier.h>
#import <SciChart/SCITooltipModifierStyle.h>
#import <SciChart/SCITooltipDataView.h>
#import <SciChart/SCIAxisInfo.h>
#import <SciChart/SCIAxisDataView.h>
#import <SciChart/SCIAxisHitTestProvider.h>
#import <SciChart/SCIRolloverModifierStyle.h>
#import <SciChart/SCIMountainHitTestProvider.h>
#import <SciChart/SCIColumnHitTestProvider.h>
#import <SciChart/SCIOhlcHitTestProvider.h>
#import <SciChart/SCICandlestickHitTestProvider.h>
#import <SciChart/SCIAnnotationProtocol.h>
#import <SciChart/SCIAnnotationBase.h>
#import <SciChart/SCILineAnnotationStyle.h>
#import <SciChart/SCITextAnnotation.h>
#import <SciChart/SCITextAnnotationStyle.h>
#import <SciChart/SCIBoxAnnotation.h>
#import <SciChart/SCIBoxAnnotationStyle.h>
#import <SciChart/SCIAnnotationStyleEnums.h>
#import <SciChart/SCICustomAnnotation.h>
#import <SciChart/SCICustomAnnotationStyle.h>
#import <SciChart/SCILogarithmicAxisProtocol.h>
#import <SciChart/SCILogarithmicDeltaCalculator.h>
#import <SciChart/SCINiceLogScale.h>
#import <SciChart/SCILogarithmicNumericAxis.h>
#import <SciChart/SCIUniformHeatmapDataSeries.h>
#import <SciChart/SCIUniformHeatmapSeriesStyle.h>
#import <SciChart/SCIBrushPalettedTexture.h>
#import <SciChart/SCITexturedBrush.h>
#import <SciChart/SCITextureOpenGL.h>
#import <SciChart/SCITextureMetal.h>

#import <SciChart/SCIFastUniformHeatmapRenderableSeries.h>
#import <SciChart/SCIBrushTexture.h>
#import <SciChart/SCIArrayController2D.h>
#import <SciChart/SCIUniformHeatmapHitTestProvider.h>
#import <SciChart/SCIXyzSeriesInfo.h>
#import <SciChart/SCIXyzSeriesDataView.h>
#import <SciChart/SCIOhlcSeriesDataView.h>
#import <SciChart/SCIOhlcSeriesInfo.h>
#import <SciChart/SCIChartSurfaceView.h>
#import <SciChart/SCIXyyPointSeries.h>
#import <SciChart/SCIXyyDataSeries.h>
#import <SciChart/SCIFastBandRenderableSeries.h>
#import <SciChart/SCIBandSeriesStyle.h>
#import <SciChart/SCIXyySeriesInfo.h>
#import <SciChart/SCIBandHitTestProvider.h>
#import <SciChart/SCIBubbleHitTestProvider.h>
#import <SciChart/SCIXyySeriesDataView.h>
#import <SciChart/SCIBubbleRenderableSeries.h>
#import <SciChart/SCIBubbleSeriesStyle.h>
#import <SciChart/SCIStackedSeriesCollectionBase.h>
#import <SciChart/SCIStackedRenderableSeries.h>
#import <SciChart/SCIStackedMountainRenderableSeries.h>
#import <SciChart/SCIStackedMountainHitTestProvider.h>
#import <SciChart/SCIXyzDataSeries.h>
#import <SciChart/SCIXyzPointSeries.h>
#import <SciChart/SCIArrayControllerFIFO.h>
#import <SciChart/SCIBrushColoredTexture.h>
#import <SciChart/SCISpritePointMarker.h>
#import <SciChart/SCIAnnotationCollection.h>
#import <SciChart/SCICoreGraphicsPointMarker.h>
#import <SciChart/SCIAxisPinchZoomModifier.h>
#import <SciChart/UIColor+SCIConvertToHexColorCode.h>
#import <SciChart/SCIViewportManager.h>
#import <SciChart/SCIRenderPassData.h>
#import <SciChart/SCIMultiSurfaceModifier.h>
#import <SciChart/SCICategoryNumericAxis.h>
#import <SciChart/SCIAxisRangeSynchronization.h>
#import <SciChart/SCICategoryDateTimeAxis.h>
#import <SciChart/SCIAxisAreaSizeSynchronization.h>
#import <SciChart/SCICallbackHelper.h>
#import <SciChart/SCICallbackHandler.h>
#import <SciChart/SCIRangeChangedCallbackHelper.h>
#import <SciChart/SCIAxisMarkerAnnotation.h>
#import <SciChart/SCIAxisMarkerAnnotationStyle.h>
#import <SciChart/SCILegendModifierBase.h>
#import <SciChart/SCIStyleProtocol.h>
#import <SciChart/SCIPaletteProvider.h>
#import <SCIChart/SCILegendModifier.h>
#import <SciChart/SCILegendCellStyle.h>
#import <SciChart/SCILegendItem.h>
#import <SciChart/SCILegendItemViewProtocol.h>
#import <SciChart/SCIFastImpulseRenderableSeries.h>
#import <SciChart/SCIImpulseSeriesStyle.h>
#import <SciChart/SCIFastFixedErrorBarsRenderableSeries.h>
#import <SciChart/SCIFastErrorBarsRenderableSeries.h>
#import <SciChart/SCIErrorBarsSeriesStyle.h>
#import <SciChart/SCIDataSeries+XColumnEvents.h>
#import <SciChart/SCIStackedColumnRenderableSeries.h>
#import <SciChart/SCIVerticallyStackedColumnsCollection.h>
#import <SciChart/SCIHorizontallyStackedColumnsCollection.h>
#import <SciChart/SCIVerticallyStackedMountainsCollection.h>
#import <SciChart/SCICustomRenderableSeries.h>
#import <SciChart/SCIThemeColorProvider.h>
#import <SciChart/SCIThemeProviderProtocol.h>
#import <SciChart/SCIThemeableProtocol.h>
#import <SciChart/SCISeriesSelectionModifier.h>
#import <SciChart/SCIRenderableSeriesCollection.h>
#import <SciChart/SCICollectionChangedEventArgs.h>
#import <SciChart/SCIPenDashed.h>
#import <SciChart/SCIAxisMarkerAnnotationBase.h>
#import <SciChart/SCIAnnotationLabelStyle.h>
#import <SciChart/SCIPenStyle.h>
#import <SciChart/SCISolidPenStyle.h>
#import <SciChart/SCILinearGradientPenStyle.h>
#import <SciChart/SCIBrushStyle.h>
#import <SciChart/SCISolidBrushStyle.h>
#import <SciChart/SCILinearGradientBrushStyle.h>
#import <SciChart/SCITextureBrushStyle.h>
#import <SciChart/SCIObservableCollection.h>
#import <SciChart/SCIBaseMountainRenderableSeries.h>
#import <SciChart/SCIChartHeatmapColourMap.h>
#import <SciChart/SCIVerticalLineAnnotation.h>
#import <SciChart/SCIHorizontalLineAnnotation.h>
#import <SciChart/SCILineAnnotationLabel.h>
#import <SciChart/SCILineAnnotation.h>
#import <SciChart/SCIDataSeriesObserver.h>
#import <SciChart/SCICollectionObserver.h>
#import <SciChart/SCICategoryNumericLabelProvider.h>
#import <SciChart/SCIGestureController.h>
#import <SciChart/SCISuspendableProtocol.h>
#import <SciChart/SCIUpdateSuspenderProtocol.h>
#import <SciChart/SCIDisposableProtocol.h>
#import <SciChart/SCIDisposableBase.h>
#import <SciChart/SCIUpdateSuspender.h>
#import <SciChart/SCIThemeManager.h>
#import <SciChart/SCIAnnotationCreationModifier.h>
#import <SciChart/SCICreationAnnotationFactory.h>
#import <SciChart/SCIAnimation.h>
#import <SciChart/SCIScaleRenderableSeriesAnimation.h>
#import <SciChart/SCIAnimationContextInvalidate.h>
#import <SciChart/SCIOhlcRenderableSeriesAnimationProtocol.h>
#import <SciChart/SCIRenderableSeriesAnimationProtocol.h>
#import <SciChart/SCICandleStickRenderableSeriesAnimationProtocol.h>
#import <SciChart/SCIBubbleRenderableSeriesAnimationProtocol.h>
#import <SciChart/SCIMountainRenderableSeriesAnimationProtocol.h>
#import <SciChart/SCIScatterRenderableSeriesAnimationProtocol.h>
#import <SciChart/SCIColumnRenderableSeriesAnimationProtocol.h>
#import <SciChart/SCIBandRenderableSeriesAnimationProtocol.h>
#import <SciChart/SCIErrorBarsRenderableSeriesAnimationProtocol.h>
#import <SciChart/SCIFixedErrorBarsRenderableSeriesAnimationProtocol.h>
#import <SciChart/SCIOhlcPointSeriesAnimatorProtocol.h>
#import <SciChart/SCIStackedSeriesCollectionAnimnationProtocol.h>
#import <SciChart/SCIHlcPointSeriesAnimatorProtocol.h>
#import <SciChart/SCIXyzPointSeriesAnimatorProtocol.h>
#import <SciChart/SCIXyyPointSeriesAnimatorProtocol.h>
#import <SciChart/SCISweepRenderableSeriesAnimation.h>
#import <SciChart/SCIWaveRenderableSeriesAnimation.h>
#import <SciChart/SCIFadeRenderableSeriesAnimation.h>
#import <SciChart/SCIPieRenderableSeries.h>
#import <SciChart/SCIPieDonutRenderableSeriesBase.h>
#import <SciChart/SCIPieSegment.h>
#import <SciChart/SCIPieChartSurface.h>
#import <SciChart/SCIPieSelectionModifier.h>
#import <SciChart/SCIPieTooltipModifier.h>
#import <SciChart/SCIPieTooltipView.h>
#import <SCIChart/SCIDonutRenderableSeries.h>
#import <SciChart/SCIPieRenderableSeriesProtocol.h>
#import <SciChart/SCIPieLayoutPassData.h>
#import <SciChart/SCIPieRenderPassData.h>
#import <SciChart/SCIRadialGradientBrushStyle.h>
#import <SciChart/SCIPieRenderableSeriesCollection.h>
#import <SciChart/SCIPieLayoutManager.h>
#import <SciChart/SCIPieSegmentCollection.h>
#import <SciChart/SCIPieHitTestInfo.h>
#import <SciChart/SCIPieHitTestProvider.h>
#import <SciChart/SCIPieLegendModifier.h>
#import <SciChart/SCIPieSeriesInfo.h>
#import <SciChart/SCIPieSeriesDataView.h>
#import <SciChart/SCILegendItemView.h>

#import <SciChart/SCITickProviderProtocol.h>
#import <SciChart/SCINumericTickProvider.h>
#import <SciChart/SCILogarithmicNumericTickProvider.h>
#import <SciChart/SCICategoryDateTimeTickProvider.h>
#import <SciChart/SCICategoryTickProvider.h>
#import <SciChart/SCITimeSpanTickProviderBase.h>
#import <SciChart/SCIDateTimeTickProvider.h>

#import <SciChart/SCIFormatterLabelProviderBase.h>
#import <SciChart/SCITradeChartAxisLabelProvider.h>
#import <SciChart/SCILabelProviderBase.h>
#import <SciChart/SCINumericLabelProvider.h>
#import <SciChart/SCILabelProviderProtocol.h>
#import <SciChart/SCICategoryLabelProviderProtocol.h>
#import <SciChart/SCICategoryLabelProviderBase.h>
#import <SciChart/SCILogarithmicNumericLabelProvider.h>
#import <SciChart/SCIDateTimeLabelProvider.h>
#import <SciChart/SCICategoryDateTimeLabelProvider.h>

#import <SciChart/NSDateFormatter+Util.h>
#import <SciChart/SCIScientificNotation.h>
#import <SciChart/SCILabelFormatterProtocol.h>
#import <SciChart/SCISimpleNumericLabelFormatter.h>
#import <SciChart/SCIScientificNumericLabelFormatter.h>
#import <SciChart/SCILogBaseNumericLabelFormatter.h>
#import <SciChart/SCIDateLabelFormatter.h>

#import <SciChart/SCINumericLabelFormatterBase.h>
#import <SciChart/SCINumericLabelFormatter.h>
#import <SciChart/SCILogarithmicNumericLabelFormatter.h>
#import <SciChart/SCITradeChartAxisLabelFormatter.h>

#import <SciChart/SCIStringUtil.h>
#import <SciChart/SCISourceMode.h>
#import <SciChart/SCILegendPosition.h>
#import <SciChart/SCIDefaultLegendItemBase.h>
#import <SciChart/SCIDefaultLegendItem.h>
#import <SciChart/SCIDefaultPieLegendItem.h>
#import <SciChart/SCILegendDataSource.h>
#import <SciChart/SCILegendItemProtocol.h>
#import <SciChart/SCIChartLegend.h>
#import <SciChart/SCIChartLegendHorizontalLayout.h>
#import <SciChart/SCIChartLegendVerticalLayout.h>
#import <SciChart/SCISeriesInfoLegendDataSource.h>
#import <SciChart/SCIPieSegmentsLegendDataSource.h>
#import <SciChart/SCILegendDataSourceProtocol.h>

#import <SciChart/SCIVisibleRangeAnimatorProtocol.h>
//#import <SciChart/.h>
//#import <SciChart/.h>
//#import <SciChart/.h>
//#import <SciChart/.h>
